site_name: Home - E-Commerce Product Classification
site_description: Prediksi Klasifikasi Produk Toko Online
site_author: Prasetyo Widyantoro
copyright: Prasetyowidyantoro12@2023
nav:
  - DOKUMENTASI: index.md
  - TENTANG SAYA: about.md
theme: 
  name: readthedocs